# Generated by Django 3.2 on 2021-04-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ylenh', '0004_auto_20210419_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ylenh',
            old_name='username_id',
            new_name='username',
        ),
    ]
