# Generated by Django 3.2 on 2021-04-19 03:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ylenh', '0005_rename_username_id_ylenh_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ylenh',
            name='username',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL),
        ),
    ]
