# Generated by Django 3.2 on 2021-04-21 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ylenh', '0006_alter_ylenh_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ylenh',
            name='title',
            field=models.TextField(default='Y Lenh'),
        ),
        migrations.AlterField(
            model_name='ylenh',
            name='username',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
