# Generated by Django 3.2 on 2021-05-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('ylenh', '0009_ylenh_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ylenh',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='ylenh',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Fail', 'Fail'), ('Doing', 'Doing')], default='Doing', max_length=12),
        ),
    ]
