# Generated by Django 3.2 on 2021-05-10 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ylenh', '0011_ylenh_day_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ylenh',
            name='day_update',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
    ]
